### ISSUE TITLE
[Bug] Empty Message in 2.3.2

### ISSUE THREAD

**Issue by amazzoccone** [Ph3nol/NotificationPusher#161]
I have a project with Laravel 5.5 and PHP 7.1 and it sends an empty Push Notification.
I rollback version to 2.3.0 and works correctly.

**Comment by seyfer** [comment]
@amazzoccone, please try 2.3.3

**Comment by aliemam** [comment]
it is because of function `getServiceMessageFromOrigin()` in Gcm.php in Adapters.
according to [Gcm Doc](https://developers.google.com/cloud-messaging/concept-options#target) when you send notification if the app run in background and you fill the field _notification_ it does not work and you have to send your data with field _data_. ( refer to this [issue](https://stackoverflow.com/questions/35480573/gcmlistenerservice-is-not-called-when-application-is-in-background) ) in 2.3.3 function above fill both _notification_ and _data_ but in 2.3.0 it just fill _data_. that is why when you rolled back it worked.
